name: awesome-lint
on:
  pull_request:
  workflow_dispatch:
  push:
jobs:
  awesome-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: cachix/install-nix-action@V27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
      - run: nix develop .# --command "awesome-lint"
        name: "Run the awesome-lint linter"
