name: Checks
on:
  pull_request:
  push:
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@V27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
      - uses: DeterminateSystems/magic-nix-cache-action@7f56db3553dc65c9ad85259996828b6bede3a1fb
      - run: nix develop .# --command just vale
        name: "Run the Vale linter"
      - run: nix develop .# --command just awesome-lint
        name: "Run the awesome-lint linter"
