name: Vale
on:
  pull_request:
  push:
jobs:
  awesome-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@V27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
      - run: nix develop .# --command "just vale"
        name: "Run the Vale linter"
